import type { PolicyPoint } from "./points";

export const policyPointsEn: PolicyPoint[] = [
  {
    id: 1,
    title: "Every Language Is a Superpower",
    subtitle: "Intensive Swedish from day one – but also multilingual public services and the right to use your skills in any language",
    body: "We introduce a completely new model: every newly arrived person is immediately offered an intensive, fully funded Swedish course with full compensation and childcare. But we don't stop there. We build a society that recognises that a Somali-speaking doctor can save lives in Somali while learning Swedish. That an Arabic-speaking engineer can solve technical problems in Arabic from week one. Every participant is paired with a mentor – not a bureaucrat, but a fellow human being. We invest 25 billion SEK annually and create the world's most ambitious language programme: SFI 2.0 with parallel career tracks in the mother tongue. Multilingual public services become standard across all government agencies. Canada and New Zealand have shown that early, generous language investments pay for themselves many times over – we go further by treating every language as a national asset.",
    quote: "A new language is a new life. But the old language isn't dead – it's your superpower.",
    quoteAuthor: "Adapted from a Persian proverb",
    category: "Language & Diversity",
    metrics: [
      { label: "Annual investment", value: "25B SEK", icon: "money" },
      { label: "People reached/year", value: "180,000", icon: "people" },
      { label: "Languages in public services", value: "40+", icon: "globe" },
      { label: "Expected GDP effect", value: "+0.8% annually", icon: "chart" },
      { label: "Mentors to recruit", value: "50,000", icon: "people" },
      { label: "Implementation time", value: "18 months", icon: "clock" },
    ],
  },
  {
    id: 2,
    title: "The Key to the Door",
    subtitle: "State housing guarantee, 300,000 new homes and an end to segregation through architecture",
    body: "The housing crisis is not an immigration problem – it's a political failure that affects everyone. We launch the largest housing programme since the Million Programme: 300,000 new homes in five years, with requirements for mixed tenure in every neighbourhood. No municipality escapes. We introduce a state housing guarantee giving every newly arrived family a contract within 30 days. But we don't just build homes – we build neighbourhoods. Every new area is designed with meeting places, communal kitchens, multilingual libraries and cultural centres. Segregation is fought by building it away – not by pointing fingers at those who live in it. Vienna has shown that public housing creates stable, mixed neighbourhoods where rent never exceeds 25% of income.",
    quote: "To have a home is to have a future. To have a neighbourhood is to have a society.",
    quoteAuthor: "Desmond Tutu (adapted)",
    category: "Housing & Society",
    metrics: [
      { label: "Total investment", value: "450B SEK", icon: "money" },
      { label: "New homes", value: "300,000", icon: "building" },
      { label: "New jobs created", value: "120,000", icon: "people" },
      { label: "Municipalities participating", value: "All 290", icon: "building" },
      { label: "Max rent share of income", value: "25%", icon: "chart" },
      { label: "Implementation time", value: "5 years", icon: "clock" },
    ],
  },
  {
    id: 3,
    title: "Your Profession Counts – In Every Language",
    subtitle: "90-day validation guarantee, bridging education with salary and multilingual workplaces",
    body: "It's a scandal that doctors drive taxis and engineers clean stairwells – not because there's anything wrong with driving taxis or cleaning, but because we're wasting skills we desperately need. We introduce a 90-day guarantee for validation of foreign qualifications. But we go further: during the validation process, you work in your profession under supervision – a Syrian surgeon assists in the operating room from week one, not after three years of waiting. We create 50 regional validation centres with industry experts and interpreters. Multilingual workplaces become the norm, not the exception. An Arabic-speaking dentist treating Arabic-speaking patients doesn't do a worse job – they do a better one. Sweden already ranks second in the Global Innovation Index – imagine what we could do if we actually used all the expertise that's already here.",
    quote: "Don't waste people's talent. It's the one resource we never get back.",
    quoteAuthor: "",
    category: "Work & Skills",
    metrics: [
      { label: "Annual investment", value: "18B SEK", icon: "money" },
      { label: "Validations per year", value: "85,000", icon: "people" },
      { label: "Validation centres", value: "50 regional", icon: "building" },
      { label: "Societal savings", value: "35B SEK/year", icon: "chart" },
      { label: "Max waiting time", value: "90 days", icon: "clock" },
      { label: "Industries in programme", value: "120+", icon: "globe" },
    ],
  },
  {
    id: 4,
    title: "Start Sweden",
    subtitle: "A 30 billion startup fund, startup visas and the world's simplest business registration",
    body: "Immigrants start businesses at a higher rate than native-born Swedes – and they bring global networks, new markets and business ideas we'd never have come up with ourselves. Yet they face more barriers: no bank contacts, no credit history, no one who understands their business idea. We create a Startup Fund of 30 billion SEK with microloans, advisory services and coworking hubs in every municipality. Business registration should take a day, not a month – in any language. We introduce a startup visa making Sweden the most attractive country in Europe for international entrepreneurs. Every new business owner gets a business mentor and access to a global network. In the US, immigrants have founded over half of all unicorn companies. We want the same power here – and we have better conditions.",
    quote: "Entrepreneurship is the ultimate engine of integration. And the best export.",
    quoteAuthor: "",
    category: "Business & Innovation",
    metrics: [
      { label: "Fund capital", value: "30B SEK", icon: "money" },
      { label: "New businesses/year", value: "25,000", icon: "building" },
      { label: "New jobs (5 years)", value: "150,000", icon: "people" },
      { label: "Tax revenue (5 years)", value: "+45B SEK", icon: "chart" },
      { label: "Coworking hubs", value: "290 (one/municipality)", icon: "building" },
      { label: "Startup visas/year", value: "10,000", icon: "globe" },
    ],
  },
  {
    id: 5,
    title: "Children First, Always",
    subtitle: "Universal preschool from age 1, multilingual pedagogy and every child's mother tongue as an asset",
    body: "No child should start school at a disadvantage because their parents came from another country. We introduce universal preschool from age one with multilingual pedagogy – the child's mother tongue is an asset, not a problem. A child who speaks Dari at home and Swedish at school doesn't have one language too many – they have one more language than most. Every school with more than 20% multilingual pupils gets double resources, not fewer. Homework help becomes a statutory right – in Swedish and in the mother tongue. We recruit 15,000 multilingual educators and pay them as specialists. Research from the OECD shows that early educational investments yield the highest return of all societal investments – and that multilingual children develop stronger cognitive abilities.",
    quote: "Education is the most powerful weapon which you can use to change the world.",
    quoteAuthor: "Nelson Mandela",
    category: "Education & Children",
    metrics: [
      { label: "Annual investment", value: "35B SEK", icon: "money" },
      { label: "Children reached", value: "350,000", icon: "people" },
      { label: "New educators", value: "15,000", icon: "people" },
      { label: "Languages in preschool", value: "60+", icon: "globe" },
      { label: "Return per krona", value: "7:1 (OECD)", icon: "chart" },
      { label: "Full rollout", value: "3 years", icon: "clock" },
    ],
  },
  {
    id: 6,
    title: "Citizenship as a Welcome Embrace",
    subtitle: "Faster path to citizenship, municipal voting rights after one year and ceremonies that matter",
    body: "We shorten the path to citizenship to three years for those who work, study or run a business. But we also make the citizenship ceremony something grand and beautiful – a national celebration, not a stamp on a piece of paper. Every new citizen receives a personal invitation, a mentor and a voice in society. We introduce municipal voting rights after one year – because those who live here should be able to influence their neighbourhood. Belonging is not created by keeping people at a distance – it's created by inviting them in. The ceremony is held in Swedish and in the new citizen's mother tongue. New Zealand and Canada have shown that generous citizenship rules strengthen, not weaken, national cohesion.",
    quote: "Belonging is not a reward. It's a prerequisite for everything else.",
    quoteAuthor: "",
    category: "Democracy & Belonging",
    metrics: [
      { label: "Annual investment", value: "3B SEK", icon: "money" },
      { label: "New citizens/year", value: "100,000", icon: "people" },
      { label: "Time to citizenship", value: "3 years (from 5)", icon: "clock" },
      { label: "Municipal voting after", value: "1 year", icon: "chart" },
      { label: "Ceremonies per year", value: "4 national", icon: "building" },
      { label: "Socioeconomic gain", value: "+12B SEK/year", icon: "chart" },
    ],
  },
  {
    id: 7,
    title: "Neighbourhoods Without Borders",
    subtitle: "Neighbourhood contracts with 15 billion annually, local investment pacts and neighbourhood councils with real power",
    body: "We introduce Neighbourhood Contracts – binding agreements between municipalities, businesses and residents in every district. The contracts guarantee investments in schools, parks, public transport and workplaces in exchange for local engagement. Every contract is managed by a neighbourhood council where half the seats are reserved for newcomers. We allocate 15 billion annually to a Neighbourhood Fund. Every district gets a meeting place – a People's House New Sweden – with a multilingual library, communal kitchen, music rooms and digital workshop. France has tested similar models in its banlieues with measurable results – we take the concept further, scale it up and make it an international standard.",
    quote: "It takes a village to raise a child – and an entire neighbourhood to build a society.",
    quoteAuthor: "",
    category: "Housing & Society",
    metrics: [
      { label: "Annual investment", value: "15B SEK", icon: "money" },
      { label: "Districts with contracts", value: "1,500", icon: "building" },
      { label: "Neighbourhood councils", value: "1,500", icon: "people" },
      { label: "People's Houses New Sweden", value: "500", icon: "building" },
      { label: "Expected safety improvement", value: "+40%", icon: "chart" },
      { label: "Implementation time", value: "4 years", icon: "clock" },
    ],
  },
  {
    id: 8,
    title: "Healthcare as a Bridge",
    subtitle: "Multilingual primary care as standard, trauma treatment within 30 days and 10,000 health ambassadors",
    body: "Health is the foundation for everything else – and healthcare is the perfect example of why multilingualism saves lives. A patient who can describe their symptoms in their mother tongue receives better care. Period. We expand primary care with multilingual health centres in every municipality and hire 10,000 health ambassadors – people with their own migration experience who guide newcomers through the healthcare system. Mental health is prioritised: trauma treatment must be offered within 30 days, not 18 months, and in the language the patient knows best. We invest 20 billion in a healthcare reform that recognises that body and mind cannot be integrated separately – and that language is part of the medicine.",
    quote: "A healthy person has a thousand dreams. A sick person has only one.",
    quoteAuthor: "Indian proverb",
    category: "Health & Care",
    metrics: [
      { label: "Annual investment", value: "20B SEK", icon: "money" },
      { label: "Health ambassadors", value: "10,000", icon: "people" },
      { label: "Multilingual health centres", value: "290+", icon: "building" },
      { label: "Max wait for trauma care", value: "30 days", icon: "clock" },
      { label: "Languages in primary care", value: "35+", icon: "globe" },
      { label: "Sick leave savings", value: "8B SEK/year", icon: "chart" },
    ],
  },
  {
    id: 9,
    title: "Cultural Power",
    subtitle: "5 billion for cross-cultural creation, Cultural Houses New Sweden in every municipality and a new national prize",
    body: "Culture is not the icing on the cake – it is the cake. And cultural diversity is not a problem to manage but a creative explosion waiting to happen. We invest 5 billion SEK annually in a national cultural exchange programme: art houses, music venues, film funds and literary grants that specifically support cross-cultural creation. Every municipality gets a Cultural House New Sweden – a meeting place for stories, food, music and art from around the world. We establish the New Sweden Prize for those who best contribute to cultural renewal. We fund 1,000 artist grants annually for creators with international backgrounds. Berlin's cultural renaissance after the fall of the Wall shows what happens when cultures meet freely – we build that in every Swedish municipality.",
    quote: "Culture eats strategy for breakfast. And diversity eats boredom for lunch.",
    quoteAuthor: "Peter Drucker (very freely)",
    category: "Culture & Identity",
    metrics: [
      { label: "Annual investment", value: "5B SEK", icon: "money" },
      { label: "Cultural Houses New Sweden", value: "290", icon: "building" },
      { label: "Artist grants/year", value: "1,000", icon: "people" },
      { label: "Cultural tourism (forecast)", value: "+15B SEK/year", icon: "chart" },
      { label: "New cultural jobs", value: "20,000", icon: "people" },
      { label: "Film fund", value: "2B SEK", icon: "money" },
    ],
  },
  {
    id: 10,
    title: "Digital Right of Public Access",
    subtitle: "Free broadband, AI-powered public services in 40 languages and 100,000 tech education places",
    body: "We make digital access a fundamental right. Every resident gets free broadband, a digital identity and access to AI-powered public services in their own language – not as a translation service added afterwards, but as a core function. We launch the largest tech education programme in European history: 100,000 places annually in programming, AI and digital skills, with special priority for newcomers. Education takes place in Swedish and in parallel in the participant's mother tongue. Sweden already ranks among the world's most digitalised countries. Now we take the step to become the first country where no one is left behind in the digital revolution – and where multilingual AI becomes an export product.",
    quote: "The future belongs to those who learn new skills and find new ways to use them.",
    quoteAuthor: "",
    category: "Digitalisation & Future",
    metrics: [
      { label: "Annual investment", value: "22B SEK", icon: "money" },
      { label: "Tech education places/year", value: "100,000", icon: "people" },
      { label: "Languages in AI services", value: "40+", icon: "globe" },
      { label: "Digital export potential", value: "50B SEK/year", icon: "chart" },
      { label: "Broadband to households", value: "100%", icon: "building" },
      { label: "Full rollout", value: "3 years", icon: "clock" },
    ],
  },
  {
    id: 11,
    title: "New Rules for the Labour Market",
    subtitle: "Anonymous recruitment by law, diversity bonus and multilingualism as a merit in all public positions",
    body: "We introduce anonymous recruitment by law for all employers with more than 10 employees. Companies that actively recruit from underrepresented groups receive a diversity bonus – a tax reduction of 20% of salary costs during the first year. But we go further: multilingualism becomes a formal merit in all public positions. Speaking Tigrinya and Swedish is not just as good as speaking only Swedish – it's better. The Equality Ombudsman gets quadrupled resources and the right to impose significant fines. We create industry-specific integration programmes in collaboration with trade unions and employers. The goal: within five years, the employment gap between native and foreign-born should be eliminated.",
    quote: "Diversity is being invited to the party. Inclusion is being asked to dance.",
    quoteAuthor: "Vernā Myers",
    category: "Work & Skills",
    metrics: [
      { label: "Annual investment", value: "12B SEK", icon: "money" },
      { label: "Employers affected", value: "85,000", icon: "building" },
      { label: "Diversity bonus (tax reduction)", value: "20%", icon: "chart" },
      { label: "New jobs (5 years)", value: "200,000", icon: "people" },
      { label: "Equality Ombudsman's new budget", value: "×4", icon: "money" },
      { label: "Goal: employment gap", value: "0% (5 years)", icon: "clock" },
    ],
  },
  {
    id: 12,
    title: "The People's Voice – In Every Language",
    subtitle: "Multilingual citizens' councils, youth parliament and deliberative democracy as standard",
    body: "Integration is too important to be left to politicians alone. We establish permanent citizens' councils in every municipality – randomly selected residents who give binding recommendations on local issues. All councils work multilingually with simultaneous interpretation. We create a national youth parliament for integration with real power and a budget of 500 million SEK. Every major reform is preceded by deliberative processes where newcomers and established Swedes meet face to face – on each other's terms. Ireland's citizens' assembly showed that ordinary people can solve issues politicians don't dare touch. We do it in 40 languages.",
    quote: "Democracy is not just voting every four years. It's listening every day – in every language.",
    quoteAuthor: "",
    category: "Democracy & Belonging",
    metrics: [
      { label: "Annual investment", value: "4B SEK", icon: "money" },
      { label: "Municipal citizens' councils", value: "290", icon: "building" },
      { label: "Youth parliament budget", value: "500M SEK", icon: "money" },
      { label: "Simultaneous interpretation languages", value: "40+", icon: "globe" },
      { label: "Participants per year", value: "50,000", icon: "people" },
      { label: "Binding recommendations", value: "Yes", icon: "chart" },
    ],
  },
  {
    id: 13,
    title: "Green New Land",
    subtitle: "200,000 green jobs, the climate transition as an integration project and Sweden as a global role model",
    body: "The climate transition and integration are not competing projects – they are the same project. We create 200,000 green jobs specifically targeted at newcomers: solar panel installers, wind power technicians, circular economy specialists, urban farmers, climate researchers. Every job comes with education and certification – in Swedish and in the mother tongue. We make Sweden the first country in the world to link its climate plan with its integration plan. Many newcomers come from countries hardest hit by climate change – their knowledge and experience is invaluable. Lund University already ranks as the world's most sustainable – now we build an entire country in that spirit.",
    quote: "We don't inherit the earth from our parents. We borrow it from our children – all our children.",
    quoteAuthor: "",
    category: "Climate & Sustainability",
    metrics: [
      { label: "Annual investment", value: "40B SEK", icon: "money" },
      { label: "Green jobs", value: "200,000", icon: "people" },
      { label: "CO₂ reduction", value: "-25% (5 years)", icon: "chart" },
      { label: "Green export potential", value: "80B SEK/year", icon: "chart" },
      { label: "Education programmes", value: "50 certifications", icon: "building" },
      { label: "Implementation time", value: "5 years", icon: "clock" },
    ],
  },
  {
    id: 14,
    title: "The Story of Us",
    subtitle: "A new national narrative, a migration museum and a curriculum that reflects reality",
    body: "We need a new story about Sweden. Not the one about a threatened homogeneous paradise, but the one about a country that has always changed and always grown stronger from it. The Walloons built our ironworks. Finnish war children became our teachers. Chileans brought a democracy movement. Iranians started our tech companies. Somalis run our small businesses. We invest in research, journalism and public education that makes immigration's contributions visible throughout history. We create a national museum of migration and movement – not as a monument to the past, but as a living story about the future. We change the curriculum so every child learns that Sweden has always been a country in motion. Stories shape reality – and we choose a story that opens doors.",
    quote: "Whoever controls the narrative controls the future. Let's tell a better story.",
    quoteAuthor: "",
    category: "Culture & Identity",
    metrics: [
      { label: "Annual investment", value: "8B SEK", icon: "money" },
      { label: "Migration museum", value: "1 national + 50 local", icon: "building" },
      { label: "Research positions", value: "500", icon: "people" },
      { label: "New curriculum", value: "All grades", icon: "globe" },
      { label: "Public education programmes", value: "10,000 circles/year", icon: "people" },
      { label: "Implementation time", value: "2 years", icon: "clock" },
    ],
  },
  {
    id: 15,
    title: "Measurable, Transparent, Honest",
    subtitle: "Annual integration report with open data, clear goals and political accountability – in every language",
    body: "Everything we do shall be measured, published and debated – openly, honestly and in every language. We introduce an annual national integration report with open data – not to control people, but to hold politics accountable. Every point in this programme gets measurable goals and a responsible minister. Results are presented in parliament and on an open digital platform – accessible in 40 languages – where every citizen can follow progress in their municipality. If we fail, it should be visible. If we succeed, it should be celebrated. We create an independent integration authority with the mandate to review, evaluate and propose changes. Transparency is not a weakness – it's the strongest tool we have.",
    quote: "What gets measured gets done. What's visible gets better. What's shared gets stronger.",
    quoteAuthor: "",
    category: "Governance & Transparency",
    metrics: [
      { label: "Annual investment", value: "2B SEK", icon: "money" },
      { label: "Open data platform", value: "40+ languages", icon: "globe" },
      { label: "Responsible ministers", value: "15 (one per point)", icon: "people" },
      { label: "Independent authority", value: "New", icon: "building" },
      { label: "Review frequency", value: "Quarterly", icon: "clock" },
      { label: "Total programme cost/year", value: "~250B SEK", icon: "money" },
    ],
  },
];

export const categoriesEn = [
  "All",
  "Language & Diversity",
  "Housing & Society",
  "Work & Skills",
  "Business & Innovation",
  "Education & Children",
  "Democracy & Belonging",
  "Health & Care",
  "Culture & Identity",
  "Digitalisation & Future",
  "Climate & Sustainability",
  "Governance & Transparency",
];
