/*
 * Det Nya Sverige – 15 Punkter
 * Design: Nordic Monumentalism (Warm Light)
 * Each point: number, title, subtitle, body, quote, category + data metrics
 */

export interface DataMetric {
  label: string;
  value: string;
  icon: "money" | "people" | "chart" | "clock" | "building" | "globe";
}

export interface PolicyPoint {
  id: number;
  title: string;
  subtitle: string;
  body: string;
  quote: string;
  quoteAuthor: string;
  category: string;
  metrics: DataMetric[];
}

export const policyPoints: PolicyPoint[] = [
  {
    id: 1,
    title: "Alla språk är superkrafter",
    subtitle: "Intensiv svenska från dag ett – men också flerspråkig samhällsservice och rätten att använda sin kompetens på alla språk",
    body: "Vi inför en helt ny modell: varje nyanländ person erbjuds omedelbart en intensiv, heltidsfinansierad svenskutbildning med full ersättning och barnomsorg. Men vi slutar inte där. Vi bygger ett samhälle som erkänner att en somalisktalande läkare kan rädda liv på somaliska medan hen lär sig svenska. Att en arabisktalande ingenjör kan lösa tekniska problem på arabiska redan första veckan. Varje deltagare kopplas till en mentor – inte en byråkrat, utan en medmänniska. Vi investerar 25 miljarder kronor årligen och skapar världens mest ambitiösa språkprogram: SFI 2.0 med parallella yrkesbanor på modersmålet. Flerspråkig samhällsservice blir standard i alla myndigheter. Kanada och Nya Zeeland har visat att tidiga, generösa språkinvesteringar betalar sig mångfalt – vi tar det längre genom att se alla språk som nationella tillgångar.",
    quote: "Ett nytt språk är ett nytt liv. Men det gamla språket är inte dött – det är din superkraft.",
    quoteAuthor: "Fritt efter persiskt ordspråk",
    category: "Språk & Mångfald",
    metrics: [
      { label: "Årlig investering", value: "25 mdr kr", icon: "money" },
      { label: "Berörda per år", value: "180 000", icon: "people" },
      { label: "Språk i samhällsservice", value: "40+", icon: "globe" },
      { label: "Förväntad BNP-effekt", value: "+0,8% årligen", icon: "chart" },
      { label: "Mentorer att rekrytera", value: "50 000", icon: "people" },
      { label: "Genomförandetid", value: "18 månader", icon: "clock" },
    ],
  },
  {
    id: 2,
    title: "Nyckeln till dörren",
    subtitle: "Statlig bostadsgaranti, 300 000 nya bostäder och ett slut på segregationen genom arkitektur",
    body: "Bostadskrisen är inte ett invandringsproblem – det är ett politiskt misslyckande som drabbar alla. Vi lanserar det största bostadsprogrammet sedan miljonprogrammet: 300 000 nya bostäder på fem år, med krav på blandade upplåtelseformer i varje kvarter. Ingen kommun slipper undan. Vi inför en statlig bostadsgaranti som ger varje nyanländ familj ett kontrakt inom 30 dagar. Men vi bygger inte bara bostäder – vi bygger grannskap. Varje nytt område designas med mötesplatser, gemensamma kök, flerspråkiga bibliotek och kulturhus. Segregation bekämpas genom att bygga bort den – inte genom att peka finger åt dem som bor i den. Wien har visat att offentligt bostadsbyggande skapar stabila, blandade stadsdelar där hyran aldrig överstiger 25% av inkomsten.",
    quote: "Att ha ett hem är att ha en framtid. Att ha ett grannskap är att ha ett samhälle.",
    quoteAuthor: "Desmond Tutu (fritt)",
    category: "Bostad & Samhälle",
    metrics: [
      { label: "Total investering", value: "450 mdr kr", icon: "money" },
      { label: "Nya bostäder", value: "300 000", icon: "building" },
      { label: "Nya arbetstillfällen", value: "120 000", icon: "people" },
      { label: "Kommuner som deltar", value: "Alla 290", icon: "building" },
      { label: "Max hyresandel av inkomst", value: "25%", icon: "chart" },
      { label: "Genomförandetid", value: "5 år", icon: "clock" },
    ],
  },
  {
    id: 3,
    title: "Ditt yrke räknas – på alla språk",
    subtitle: "90-dagarsgaranti för validering, kompletteringsutbildning med lön och flerspråkiga arbetsplatser",
    body: "Det är en skandal att läkare kör taxi och ingenjörer städar trapphus – inte för att det är fel att köra taxi eller städa, utan för att vi slösar bort kompetens vi desperat behöver. Vi inför en 90-dagarsgaranti för validering av utländska utbildningar. Men vi går längre: under valideringsprocessen arbetar du inom ditt yrke med handledning – en syrisk kirurg assisterar på operationssalen från vecka ett, inte efter tre års väntan. Vi skapar 50 regionala valideringscentra med branschexperter och tolkar. Flerspråkiga arbetsplatser blir norm, inte undantag. En arabisktalande tandläkare som behandlar arabisktalande patienter gör inte ett sämre jobb – hen gör ett bättre jobb. Sverige rankas redan tvåa i Global Innovation Index – tänk vad vi kan göra om vi faktiskt använder all den kompetens som redan finns här.",
    quote: "Slösa inte med människors talang. Det är den enda resursen vi aldrig får tillbaka.",
    quoteAuthor: "",
    category: "Arbete & Kompetens",
    metrics: [
      { label: "Årlig investering", value: "18 mdr kr", icon: "money" },
      { label: "Valideringar per år", value: "85 000", icon: "people" },
      { label: "Valideringscentra", value: "50 regionala", icon: "building" },
      { label: "Samhällsbesparing", value: "35 mdr kr/år", icon: "chart" },
      { label: "Max väntetid", value: "90 dagar", icon: "clock" },
      { label: "Branscher i programmet", value: "120+", icon: "globe" },
    ],
  },
  {
    id: 4,
    title: "Starta Sverige",
    subtitle: "Nystartsfond på 30 miljarder, startup-visum och världens enklaste företagsregistrering",
    body: "Invandrare startar företag i högre grad än infödda svenskar – och de tar med sig globala nätverk, nya marknader och affärsidéer vi aldrig hade kommit på själva. Ändå möter de fler hinder: inga bankkontakter, ingen kredithistorik, ingen som förstår deras affärsidé. Vi skapar en Nystartsfond på 30 miljarder kronor med mikrolån, rådgivning och coworking-hubbar i varje kommun. Företagsregistrering ska ta en dag, inte en månad – på vilket språk som helst. Vi inför ett startup-visum som gör Sverige till Europas mest attraktiva land för internationella entreprenörer. Varje ny företagare får en affärsmentor och tillgång till ett globalt nätverk. I USA har invandrare grundat över hälften av alla unicorn-företag. Vi vill ha samma kraft här – och vi har bättre förutsättningar.",
    quote: "Entreprenörskap är den ultimata integrationsmotorn. Och den bästa exportvaran.",
    quoteAuthor: "",
    category: "Näringsliv & Innovation",
    metrics: [
      { label: "Fondkapital", value: "30 mdr kr", icon: "money" },
      { label: "Nya företag per år", value: "25 000", icon: "building" },
      { label: "Nya jobb (5 år)", value: "150 000", icon: "people" },
      { label: "Skatteintäkter (5 år)", value: "+45 mdr kr", icon: "chart" },
      { label: "Coworking-hubbar", value: "290 (en/kommun)", icon: "building" },
      { label: "Startup-visum per år", value: "10 000", icon: "globe" },
    ],
  },
  {
    id: 5,
    title: "Barnen först, alltid",
    subtitle: "Universell förskola från 1 år, flerspråkig pedagogik och varje barns modersmål som tillgång",
    body: "Inget barn ska börja skolan med ett handikapp för att föräldrarna kom från ett annat land. Vi inför universell förskola från ett års ålder med flerspråkig pedagogik – barnets modersmål är en tillgång, inte ett problem. Ett barn som talar dari hemma och svenska i skolan har inte ett språk för mycket – det har ett språk mer än de flesta. Varje skola med mer än 20% flerspråkiga elever får dubbla resurser, inte färre. Läxhjälp blir en lagstadgad rättighet – på svenska och på modersmålet. Vi rekryterar 15 000 flerspråkiga pedagoger och betalar dem som specialister. Forskning från OECD visar att tidiga utbildningsinsatser ger den högsta avkastningen av alla samhällsinvesteringar – och att flerspråkiga barn utvecklar starkare kognitiva förmågor.",
    quote: "Utbildning är det mest kraftfulla vapnet du kan använda för att förändra världen.",
    quoteAuthor: "Nelson Mandela",
    category: "Utbildning & Barn",
    metrics: [
      { label: "Årlig investering", value: "35 mdr kr", icon: "money" },
      { label: "Barn som nås", value: "350 000", icon: "people" },
      { label: "Nya pedagoger", value: "15 000", icon: "people" },
      { label: "Språk i förskolan", value: "60+", icon: "globe" },
      { label: "Avkastning per krona", value: "7:1 (OECD)", icon: "chart" },
      { label: "Full utrullning", value: "3 år", icon: "clock" },
    ],
  },
  {
    id: 6,
    title: "Medborgarskap som välkomstkram",
    subtitle: "Snabbare väg till medborgarskap, kommunal rösträtt efter ett år och ceremonier som betyder något",
    body: "Vi kortar vägen till medborgarskap till tre år för den som arbetar, studerar eller driver företag. Men vi gör också medborgarskapsceremonin till något stort och vackert – en nationell högtid, inte en stämpel på ett papper. Varje ny medborgare får en personlig inbjudan, en mentor och en röst i samhället. Vi inför kommunal rösträtt efter ett år – för den som bor här ska kunna påverka sitt grannskap. Tillhörighet skapas inte genom att hålla människor på avstånd – den skapas genom att bjuda in dem. Ceremonin hålls på svenska och på den nyblivne medborgarens modersmål. Nya Zeeland och Kanada har visat att generösa medborgarskapsregler stärker, inte försvagar, den nationella sammanhållningen.",
    quote: "Tillhörighet är inte en belöning. Det är en förutsättning för allt annat.",
    quoteAuthor: "",
    category: "Demokrati & Tillhörighet",
    metrics: [
      { label: "Årlig investering", value: "3 mdr kr", icon: "money" },
      { label: "Nya medborgare/år", value: "100 000", icon: "people" },
      { label: "Tid till medborgarskap", value: "3 år (från 5)", icon: "clock" },
      { label: "Kommunal rösträtt efter", value: "1 år", icon: "chart" },
      { label: "Ceremonier per år", value: "4 nationella", icon: "building" },
      { label: "Samhällsekonomisk vinst", value: "+12 mdr kr/år", icon: "chart" },
    ],
  },
  {
    id: 7,
    title: "Grannskap utan gränser",
    subtitle: "Grannskapskontrakt med 15 miljarder årligen, lokala investeringspakter och grannskapsråd med verklig makt",
    body: "Vi inför Grannskapskontrakt – bindande avtal mellan kommun, näringsliv och invånare i varje stadsdel. Kontrakten garanterar investeringar i skolor, parker, kollektivtrafik och arbetsplatser i utbyte mot lokalt engagemang. Varje kontrakt förvaltas av ett grannskapsråd där hälften av platserna reserveras för nyanlända. Vi avsätter 15 miljarder årligen till en Grannskapsfond. Varje stadsdel får en mötesplats – ett Folkets Hus Nya Sverige – med flerspråkigt bibliotek, gemensamt kök, musikrum och digital verkstad. Frankrike har testat liknande modeller i sina banlieues med mätbara resultat – vi tar konceptet vidare, skalar upp det och gör det till internationell standard.",
    quote: "Det krävs en hel by för att uppfostra ett barn – och en hel stadsdel för att bygga ett samhälle.",
    quoteAuthor: "",
    category: "Bostad & Samhälle",
    metrics: [
      { label: "Årlig investering", value: "15 mdr kr", icon: "money" },
      { label: "Stadsdelar med kontrakt", value: "1 500", icon: "building" },
      { label: "Grannskapsråd", value: "1 500", icon: "people" },
      { label: "Folkets Hus Nya Sverige", value: "500", icon: "building" },
      { label: "Förväntad effekt på trygghet", value: "+40%", icon: "chart" },
      { label: "Genomförandetid", value: "4 år", icon: "clock" },
    ],
  },
  {
    id: 8,
    title: "Vården som brygga",
    subtitle: "Flerspråkig primärvård som standard, traumabehandling inom 30 dagar och 10 000 vårdambassadörer",
    body: "Hälsa är grunden för allt annat – och vården är det perfekta exemplet på varför flerspråkighet räddar liv. En patient som kan beskriva sina symtom på sitt modersmål får bättre vård. Punkt. Vi bygger ut primärvården med flerspråkiga vårdcentraler i varje kommun och anställer 10 000 vårdambassadörer – personer med egen migrationserfarenhet som guidar nyanlända genom vårdsystemet. Psykisk hälsa prioriteras: traumabehandling ska erbjudas inom 30 dagar, inte 18 månader, och på det språk patienten behärskar bäst. Vi investerar 20 miljarder i en vårdreform som erkänner att kropp och själ inte kan integreras var för sig – och att språket är en del av medicinen.",
    quote: "En frisk människa har tusen drömmar. En sjuk människa har bara en.",
    quoteAuthor: "Indiskt ordspråk",
    category: "Hälsa & Omsorg",
    metrics: [
      { label: "Årlig investering", value: "20 mdr kr", icon: "money" },
      { label: "Vårdambassadörer", value: "10 000", icon: "people" },
      { label: "Flerspråkiga vårdcentraler", value: "290+", icon: "building" },
      { label: "Max väntetid trauma", value: "30 dagar", icon: "clock" },
      { label: "Språk i primärvården", value: "35+", icon: "globe" },
      { label: "Besparing sjukfrånvaro", value: "8 mdr kr/år", icon: "chart" },
    ],
  },
  {
    id: 9,
    title: "Kulturkraft",
    subtitle: "5 miljarder till tvärkulturellt skapande, Kulturhus Nya Sverige i varje kommun och ett nytt nationellt pris",
    body: "Kultur är inte grädde på moset – det är moset. Och kulturell mångfald är inte ett problem att hantera utan en kreativ explosion som väntar på att hända. Vi investerar 5 miljarder kronor årligen i ett nationellt kulturutbytesprogram: konsthus, musikscener, filmfonder och litteraturstipendier som specifikt stödjer tvärkulturellt skapande. Varje kommun får ett Kulturhus Nya Sverige – en mötesplats för berättelser, mat, musik och konst från hela världen. Vi inrättar Nya Sverige-priset, för den som bäst bidrar till kulturell förnyelse. Vi finansierar 1 000 konstnärsstipendier årligen för skapare med internationell bakgrund. Berlins kulturella renässans efter murens fall visar vad som händer när kulturer möts fritt – vi bygger det i varje svensk kommun.",
    quote: "Kultur äter strategi till frukost. Och mångfald äter tristess till lunch.",
    quoteAuthor: "Peter Drucker (mycket fritt)",
    category: "Kultur & Identitet",
    metrics: [
      { label: "Årlig investering", value: "5 mdr kr", icon: "money" },
      { label: "Kulturhus Nya Sverige", value: "290", icon: "building" },
      { label: "Konstnärsstipendier/år", value: "1 000", icon: "people" },
      { label: "Kulturturism (prognos)", value: "+15 mdr kr/år", icon: "chart" },
      { label: "Nya kulturjobb", value: "20 000", icon: "people" },
      { label: "Filmfond", value: "2 mdr kr", icon: "money" },
    ],
  },
  {
    id: 10,
    title: "Digital allemansrätt",
    subtitle: "Gratis bredband, AI-driven samhällsservice på 40 språk och 100 000 tech-utbildningsplatser",
    body: "Vi gör digital tillgång till en grundläggande rättighet. Varje invånare får gratis bredband, en digital identitet och tillgång till AI-driven samhällsservice på sitt eget språk – inte som en översättningstjänst i efterhand, utan som en grundfunktion. Vi lanserar det största tech-utbildningsprogrammet i Europas historia: 100 000 platser årligen i programmering, AI och digital kompetens, med särskild prioritet för nyanlända. Utbildningen sker på svenska och parallellt på deltagarens modersmål. Sverige rankas redan bland världens mest digitaliserade länder. Nu tar vi steget till att bli det första landet där ingen lämnas utanför den digitala revolutionen – och där flerspråkig AI blir en exportprodukt.",
    quote: "Framtiden tillhör dem som lär sig nya färdigheter och hittar nya sätt att använda dem.",
    quoteAuthor: "",
    category: "Digitalisering & Framtid",
    metrics: [
      { label: "Årlig investering", value: "22 mdr kr", icon: "money" },
      { label: "Tech-utbildningsplatser/år", value: "100 000", icon: "people" },
      { label: "Språk i AI-service", value: "40+", icon: "globe" },
      { label: "Digital exportpotential", value: "50 mdr kr/år", icon: "chart" },
      { label: "Bredband till hushåll", value: "100%", icon: "building" },
      { label: "Full utrullning", value: "3 år", icon: "clock" },
    ],
  },
  {
    id: 11,
    title: "Arbetsmarknadens nya spelregler",
    subtitle: "Anonym rekrytering som lag, mångfaldsbonus och flerspråkighet som merit i alla offentliga tjänster",
    body: "Vi inför anonym rekrytering som lag för alla arbetsgivare med fler än 10 anställda. Företag som aktivt rekryterar från underrepresenterade grupper får en mångfaldsbonus – en skattereduktion på 20% av lönekostnaden under första året. Men vi går längre: flerspråkighet blir en formell merit i alla offentliga tjänster. Att tala tigrinja och svenska är inte bara lika bra som att bara tala svenska – det är bättre. Diskrimineringsombudsmannen får fyrdubblade resurser och rätt att utdöma kännbara böter. Vi skapar branschspecifika integrationsprogram i samarbete med fackföreningar och arbetsgivare. Målet: inom fem år ska sysselsättningsgapet mellan inrikes och utrikes födda vara borta.",
    quote: "Mångfald är att bli inbjuden till festen. Inkludering är att bli uppbjuden till dans.",
    quoteAuthor: "Vernā Myers",
    category: "Arbete & Kompetens",
    metrics: [
      { label: "Årlig investering", value: "12 mdr kr", icon: "money" },
      { label: "Berörda arbetsgivare", value: "85 000", icon: "building" },
      { label: "Mångfaldsbonus (skattereduktion)", value: "20%", icon: "chart" },
      { label: "Nya jobb (5 år)", value: "200 000", icon: "people" },
      { label: "DO:s nya budget", value: "×4", icon: "money" },
      { label: "Mål: sysselsättningsgap", value: "0% (5 år)", icon: "clock" },
    ],
  },
  {
    id: 12,
    title: "Folkets röst – på alla språk",
    subtitle: "Flerspråkiga medborgarråd, ungdomsparlament och deliberativ demokrati som standard",
    body: "Integration är för viktigt för att överlåtas åt politiker ensamma. Vi inrättar permanenta medborgarråd i varje kommun – slumpmässigt utvalda invånare som ger bindande rekommendationer om lokala frågor. Alla råd arbetar flerspråkigt med simultantolkning. Vi skapar ett nationellt ungdomsparlament för integration med verklig makt och en budget på 500 miljoner kronor. Varje stor reform föregås av deliberativa processer där nyanlända och etablerade svenskar möts öga mot öga – på varandras villkor. Irlands medborgarråd visade att vanliga människor kan lösa frågor som politiker inte vågar röra. Vi gör det på 40 språk.",
    quote: "Demokrati är inte bara att rösta vart fjärde år. Det är att lyssna varje dag – på alla språk.",
    quoteAuthor: "",
    category: "Demokrati & Tillhörighet",
    metrics: [
      { label: "Årlig investering", value: "4 mdr kr", icon: "money" },
      { label: "Kommunala medborgarråd", value: "290", icon: "building" },
      { label: "Ungdomsparlamentets budget", value: "500 mkr", icon: "money" },
      { label: "Simultantolkningsspråk", value: "40+", icon: "globe" },
      { label: "Deltagare per år", value: "50 000", icon: "people" },
      { label: "Bindande rekommendationer", value: "Ja", icon: "chart" },
    ],
  },
  {
    id: 13,
    title: "Grönt nytt land",
    subtitle: "200 000 gröna jobb, klimatomställningen som integrationsprojekt och Sverige som global förebild",
    body: "Klimatomställningen och integrationen är inte konkurrerande projekt – de är samma projekt. Vi skapar 200 000 gröna jobb specifikt riktade till nyanlända: solcellsinstallatörer, vindkraftstekniker, cirkulär ekonomi-specialister, stadsodlare, klimatforskare. Varje jobb kommer med utbildning och certifiering – på svenska och på modersmålet. Vi gör Sverige till världens första land som kopplar ihop sin klimatplan med sin integrationsplan. Många nyanlända kommer från länder som drabbas hårdast av klimatförändringarna – deras kunskap och erfarenhet är ovärderlig. Lunds universitet rankas redan som världens mest hållbara – nu bygger vi ett helt land i den andan.",
    quote: "Vi ärver inte jorden av våra föräldrar. Vi lånar den av våra barn – alla våra barn.",
    quoteAuthor: "",
    category: "Klimat & Hållbarhet",
    metrics: [
      { label: "Årlig investering", value: "40 mdr kr", icon: "money" },
      { label: "Gröna jobb", value: "200 000", icon: "people" },
      { label: "CO₂-reduktion", value: "-25% (5 år)", icon: "chart" },
      { label: "Grön exportpotential", value: "80 mdr kr/år", icon: "chart" },
      { label: "Utbildningsprogram", value: "50 certifieringar", icon: "building" },
      { label: "Genomförandetid", value: "5 år", icon: "clock" },
    ],
  },
  {
    id: 14,
    title: "Berättelsen om oss",
    subtitle: "En ny nationell berättelse, ett migrationsmuseum och en läroplan som speglar verkligheten",
    body: "Vi behöver en ny berättelse om Sverige. Inte den om ett hotat homogent paradis, utan den om ett land som alltid har förändrats och alltid blivit starkare av det. Vallonerna byggde våra bruk. Finska krigsbarnen blev våra lärare. Chilenarna förde med sig en demokratirörelse. Iranierna startade våra techföretag. Somalierna driver våra småföretag. Vi investerar i forskning, journalistik och folkbildning som synliggör invandringens bidrag genom historien. Vi skapar ett nationellt museum för migration och rörelse – inte som ett monument över det förflutna, utan som en levande berättelse om framtiden. Vi ändrar läroplanen så att varje barn lär sig att Sverige alltid har varit ett land i rörelse. Berättelser formar verkligheten – och vi väljer en berättelse som öppnar dörrar.",
    quote: "Den som kontrollerar berättelsen kontrollerar framtiden. Låt oss berätta en bättre historia.",
    quoteAuthor: "",
    category: "Kultur & Identitet",
    metrics: [
      { label: "Årlig investering", value: "8 mdr kr", icon: "money" },
      { label: "Migrationsmuseum", value: "1 nationellt + 50 lokala", icon: "building" },
      { label: "Forskartjänster", value: "500", icon: "people" },
      { label: "Ny läroplan", value: "Alla årskurser", icon: "globe" },
      { label: "Folkbildningsprogram", value: "10 000 cirklar/år", icon: "people" },
      { label: "Genomförandetid", value: "2 år", icon: "clock" },
    ],
  },
  {
    id: 15,
    title: "Mätbart, transparent, ärligt",
    subtitle: "Årlig integrationsrapport med öppna data, tydliga mål och politiskt ansvar – på alla språk",
    body: "Allt vi gör ska mätas, publiceras och debatteras – öppet, ärligt och på alla språk. Vi inför en årlig nationell integrationsrapport med öppna data – inte för att kontrollera människor, utan för att kontrollera politiken. Varje punkt i detta program får mätbara mål och en ansvarig minister. Resultaten presenteras i riksdagen och på en öppen digital plattform – tillgänglig på 40 språk – där varje medborgare kan följa utvecklingen i sin kommun. Om vi misslyckas ska det synas. Om vi lyckas ska det firas. Vi skapar en oberoende integrationsmyndighet med mandat att granska, utvärdera och föreslå förändringar. Transparens är inte en svaghet – det är det starkaste verktyget vi har.",
    quote: "Det som mäts blir gjort. Det som syns blir bättre. Det som delas blir starkare.",
    quoteAuthor: "",
    category: "Styrning & Transparens",
    metrics: [
      { label: "Årlig investering", value: "2 mdr kr", icon: "money" },
      { label: "Öppen dataplattform", value: "40+ språk", icon: "globe" },
      { label: "Ansvariga ministrar", value: "15 (en per punkt)", icon: "people" },
      { label: "Oberoende myndighet", value: "Ny", icon: "building" },
      { label: "Uppföljningsfrekvens", value: "Kvartalsvis", icon: "clock" },
      { label: "Total programkostnad/år", value: "~250 mdr kr", icon: "money" },
    ],
  },
];

export const categories = [
  "Alla",
  "Språk & Mångfald",
  "Bostad & Samhälle",
  "Arbete & Kompetens",
  "Näringsliv & Innovation",
  "Utbildning & Barn",
  "Demokrati & Tillhörighet",
  "Hälsa & Omsorg",
  "Kultur & Identitet",
  "Digitalisering & Framtid",
  "Klimat & Hållbarhet",
  "Styrning & Transparens",
];
