/*
 * The New Sweden – 15 Points (English)
 * Core thesis: The problem isn't people, it's friction.
 * Core rule: AI where it reduces friction, humans where they exercise power.
 */

import type { PolicyPoint } from "./points";

export const policyPointsEn: PolicyPoint[] = [
  {
    id: 1,
    title: "One Sweden In, Not Fifteen Queues",
    subtitle: "A single digital path in – with a human guide and an AI guide in your pocket",
    body: "We're building a single path into Sweden: a digital onboarding experience, not an administrative obstacle course. Every person should encounter a unified interface where identity, documents, language support, health contact, school track, work track, and civic information are connected. There's both a human guide and an AI guide in your pocket: AI translates, explains, summarizes, and alerts when something is missing, while the caseworker makes assessments and takes responsibility. The state should function more like a smart platform and less like fifteen government islands playing ping-pong with people's lives. Today, people are bounced between the Migration Agency, the Employment Service, the Tax Agency, the municipality, and the Social Insurance Agency as if that were a reasonable system. It's not. It's a design problem. Digg has already approved e-identification for people without Swedish personal numbers and expanded identity matching – the tools exist, what's missing is will, pace, and design.",
    quote: "What today looks like an integration problem is often just a design problem the state hasn't taken seriously yet.",
    quoteAuthor: "",
    category: "Platform & Onboarding",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-1_4530788a.png",
    metrics: [
      { label: "Annual investment", value: "SEK 18 bn", icon: "money" },
      { label: "People reached per year", value: "200,000+", icon: "people" },
      { label: "Agencies connected", value: "15+", icon: "building" },
      { label: "Processing time (target)", value: "-70%", icon: "chart" },
      { label: "Languages in AI guide", value: "40+", icon: "globe" },
      { label: "Full rollout", value: "24 months", icon: "clock" },
    ],
  },
  {
    id: 2,
    title: "100-Day Competence Guarantee",
    subtitle: "A digital competence passport that stops starting with suspicion",
    body: "We're introducing a digital competence passport. Degrees, certificates, work samples, references, and experience are uploaded once, read by machine, compared against Swedish requirements, and result in a clear answer: approved, supplement this, or here's an alternative track. AI is used to interpret documents, match against qualification requirements, and suggest supplements. Humans make the decision, but the system must stop starting with suspicion. A document that doesn't fit a Swedish folder shouldn't erase an entire working life. Today, validation of foreign qualifications takes an average of 18 months. During that time, surgeons drive taxis and engineers clean stairwells – not because there's anything wrong with driving taxis or cleaning, but because we're wasting competence we desperately need. It's not just unfair, it's economic insanity. Sweden ranks second in the Global Innovation Index – imagine what we could do if we actually used all the competence already here.",
    quote: "A document that doesn't fit a Swedish folder shouldn't erase an entire working life.",
    quoteAuthor: "",
    category: "Competence & Work",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-2_6871597a.png",
    metrics: [
      { label: "Annual investment", value: "SEK 15 bn", icon: "money" },
      { label: "Validations per year", value: "90,000", icon: "people" },
      { label: "Max time to decision", value: "100 days", icon: "clock" },
      { label: "Societal savings", value: "SEK 40 bn/yr", icon: "chart" },
      { label: "Regional validation centers", value: "50", icon: "building" },
      { label: "Industries in system", value: "120+", icon: "globe" },
    ],
  },
  {
    id: 3,
    title: "Swedish Through Work, Not Before Work",
    subtitle: "A personal AI language coach in your pocket – connected to your job, your education, your life",
    body: "Everyone who needs it gets Swedish in their pocket: a personal language coach with speech training, occupational vocabulary, dialogue simulations, real-time translation, and feedback connected to the specific job, education, or everyday life they're in. We shouldn't have a model where people wait for years to become sufficiently Swedish before they can start contributing. Language is best learned when it's used, and AI makes it possible to practice a little, often, relevantly, and at your own level. This is perhaps the most underestimated lever of all. The OECD highlights AI as particularly promising for language training in integration. A Somali-speaking doctor can save lives in Somali while learning Swedish. An Arabic-speaking engineer can solve technical problems in Arabic from week one. Parallel competence and parallel language – not sequential. SFI in its current form is a waiting room, not a runway. We're rebuilding it from the ground up.",
    quote: "Language is best learned when it's used. Not in a classroom you've waited a year to enter.",
    quoteAuthor: "",
    category: "Language & Learning",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-3_4a486f4d.png",
    metrics: [
      { label: "Annual investment", value: "SEK 22 bn", icon: "money" },
      { label: "People reached per year", value: "180,000", icon: "people" },
      { label: "Languages in AI coach", value: "40+", icon: "globe" },
      { label: "Expected GDP effect", value: "+0.8% annually", icon: "chart" },
      { label: "Parallel career tracks", value: "80+", icon: "building" },
      { label: "Full rollout", value: "18 months", icon: "clock" },
    ],
  },
  {
    id: 4,
    title: "National Fast Track to Shortage Occupations",
    subtitle: "Digital fast tracks with validation, simulations, and AI-supported knowledge tests",
    body: "We're building digital fast tracks to shortage occupations with validation, simulations, AI-supported knowledge tests, supervised practice, and paid supplementary training. A nurse shouldn't start from zero because the state lacks imagination, and an electrician shouldn't get stuck between PDFs and binders. Technology should be used to compress the path to a Swedish license, not to create more waiting rooms. When someone can do the job, the system should help prove it faster. Sweden currently has staff shortages in over 100 occupational categories – from nursing assistants to civil engineers, from welders to specialist physicians. Meanwhile, we have tens of thousands of people with exactly that competence stuck in a system designed to slow things down. It's like having a highway with a 30 km/h speed limit. We're removing the unnecessary speed limits.",
    quote: "Technology should compress the path to a Swedish license, not create more waiting rooms.",
    quoteAuthor: "",
    category: "Competence & Work",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-4_6eec1d5e.png",
    metrics: [
      { label: "Annual investment", value: "SEK 12 bn", icon: "money" },
      { label: "Fast tracks in shortage occupations", value: "100+", icon: "building" },
      { label: "Participants per year", value: "45,000", icon: "people" },
      { label: "Time to license (target)", value: "-60%", icon: "clock" },
      { label: "Societal savings", value: "SEK 25 bn/yr", icon: "chart" },
      { label: "Internship placements", value: "30,000/yr", icon: "people" },
    ],
  },
  {
    id: 5,
    title: "First Real Job Within 180 Days",
    subtitle: "From CV theater to competence proof – AI matching that sees potential, not templates",
    body: "We're moving from CV theater to competence proof. AI-supported matching can connect people with employers based on skills, language progression, work samples, references, and actual potential – not just Swedish templates for cover letters. Every person gets a combination of a digital coach and a human job matcher. AI should replace waiting, not people. We need to stop pretending that CV writing is integration. Today, it takes an average of over two years for a newly arrived person to get their first real job. Two years of waiting, uncertainty, and competence loss. That's not just an individual problem – it's a system failure. Employers are screaming for competence while competence sits in waiting rooms. We're building the bridge between them with technology that sees what people can do, not just what they've written on paper.",
    quote: "We need to stop pretending that CV writing is integration.",
    quoteAuthor: "",
    category: "Competence & Work",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-5_f959578e.png",
    metrics: [
      { label: "Annual investment", value: "SEK 10 bn", icon: "money" },
      { label: "Matches per year", value: "120,000", icon: "people" },
      { label: "Target: time to first job", value: "180 days", icon: "clock" },
      { label: "Employers in network", value: "50,000+", icon: "building" },
      { label: "Socioeconomic gain", value: "SEK 35 bn/yr", icon: "chart" },
      { label: "Languages in matching system", value: "40+", icon: "globe" },
    ],
  },
  {
    id: 6,
    title: "Settle by Opportunity, Not by Passivity",
    subtitle: "Data showing where jobs, schools, and housing exist – not control, but real choices",
    body: "We use data to see where the jobs are, where schools work, where housing exists, and where the path to self-sufficiency is shortest. Not to move people around like chess pieces, but to give them better information and real choices. A national tool should be able to show: here are jobs in your field, here's language training, here's reasonable commuting, here are housing openings. It's strange that we accept more intelligence in a travel app than in the state's decisions about people's futures. Today, people are placed in municipalities with high unemployment, poor public transport, and few opportunities – not because it's best for them, but because it's easiest for the system. It's like giving someone a map without roads. We're building the map with roads, real-time data, and personal recommendations. Every municipality receiving newcomers should be able to show exactly what opportunities exist – and be measured on how well they deliver.",
    quote: "It's strange that we accept more intelligence in a travel app than in the state's decisions about people's futures.",
    quoteAuthor: "",
    category: "Platform & Onboarding",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-6_96568d86.png",
    metrics: [
      { label: "Annual investment", value: "SEK 8 bn", icon: "money" },
      { label: "Municipalities with real-time data", value: "All 290", icon: "building" },
      { label: "Data points per municipality", value: "200+", icon: "chart" },
      { label: "People reached per year", value: "80,000", icon: "people" },
      { label: "Time to self-sufficiency (target)", value: "-40%", icon: "clock" },
      { label: "Open data sources", value: "50+", icon: "globe" },
    ],
  },
  {
    id: 7,
    title: "Children First, Always",
    subtitle: "Digitally equipped schools for multilingualism – technology supports, the teacher leads",
    body: "Every newly arrived child should encounter a school that is digitally equipped for multilingualism. Recorded lessons, translated guardian flows, AI-supported language assistance, digital study guidance, adaptive exercises, and simple ways for home and school to understand each other should be standard, not project funding. But the principle is crystal clear: technology supports, the teacher leads. We're not building bot schools. We're giving good teachers much greater reach. The Swedish National Agency for Education emphasizes clear frameworks and teacher responsibility for AI in schools – and that's exactly right. But the frameworks should enable, not restrict. A child who speaks Dari at home and Swedish at school doesn't have one language too many – they have one language more than most. Every school with more than 20% multilingual students gets double resources, not fewer. We recruit 15,000 multilingual educators and pay them as specialists. The OECD shows that early educational investments yield the highest return of all societal investments.",
    quote: "We're not building bot schools. We're giving good teachers much greater reach.",
    quoteAuthor: "",
    category: "Children & Education",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-7_c53a25e2.png",
    metrics: [
      { label: "Annual investment", value: "SEK 35 bn", icon: "money" },
      { label: "Children reached", value: "350,000", icon: "people" },
      { label: "New multilingual educators", value: "15,000", icon: "people" },
      { label: "Return per krona", value: "7:1 (OECD)", icon: "chart" },
      { label: "Languages in school platform", value: "60+", icon: "globe" },
      { label: "Full rollout", value: "3 years", icon: "clock" },
    ],
  },
  {
    id: 8,
    title: "Hard on Exploitation, Soft on People",
    subtitle: "Data analysis exposing abuse – and a digital safe room in the worker's pocket",
    body: "We use data analysis and AI to detect sham employment, unreasonable wage levels, fraudulent companies, exploitation in subcontractor chains, and suspicious patterns of labor crime far earlier than today. At the same time, workers get a digital safe room in their pocket: contracts in their language, wage verification, rights guide, easy reporting, anonymous whistleblowing, and direct contact with support. Technology shouldn't just help the state control. It should help people understand their rights and dare to use them. Labor crime costs society an estimated SEK 100 billion annually in lost tax revenue, distorted competition, and human suffering. Those hit hardest are those with the least power to defend themselves. It's a perverse irony that the same system making it hard to get a work permit makes it easy to be exploited. We're flipping it: easy to work legally, impossible to exploit someone.",
    quote: "Technology shouldn't just help the state control. It should help people understand their rights and dare to use them.",
    quoteAuthor: "",
    category: "Rule of Law & Protection",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-8_ba9f2c48.png",
    metrics: [
      { label: "Annual investment", value: "SEK 8 bn", icon: "money" },
      { label: "Workers with digital protection", value: "500,000+", icon: "people" },
      { label: "Expected savings", value: "SEK 30 bn/yr", icon: "chart" },
      { label: "Languages in safe room", value: "40+", icon: "globe" },
      { label: "AI-supported inspections", value: "×5 more", icon: "building" },
      { label: "Implementation time", value: "18 months", icon: "clock" },
    ],
  },
  {
    id: 9,
    title: "Zero Tolerance for Discrimination",
    subtitle: "Anonymized screening, skills tests before gut feeling, and AI systems audited for bias",
    body: "We're settling accounts with both analog and digital discrimination. Public recruitment must use anonymized first screening, skills tests before gut feeling, and ongoing transparency in outcomes. AI systems used for matching, selection, or support – especially in employment and education – must be auditable, explainable, and possible to shut down if they reproduce old prejudices. It's not enough to digitize injustice. Sweden should become the country that measures bias as seriously as we measure budgets. The EU AI Act is already taking effect in stages and gives us a framework – but we're going further. The Equality Ombudsman gets quadrupled resources and the right to impose substantial fines. Multilingualism becomes a formal merit in all public positions. Speaking Tigrinya and Swedish isn't just as good as speaking only Swedish – it's better. The goal: within five years, the employment gap between native and foreign-born should be gone.",
    quote: "It's not enough to digitize injustice. Sweden should become the country that measures bias as seriously as we measure budgets.",
    quoteAuthor: "",
    category: "Rule of Law & Protection",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-9_e69d617f.png",
    metrics: [
      { label: "Annual investment", value: "SEK 6 bn", icon: "money" },
      { label: "Employers affected", value: "85,000", icon: "building" },
      { label: "Equality Ombudsman budget", value: "×4", icon: "money" },
      { label: "Target: employment gap", value: "0% (5 years)", icon: "chart" },
      { label: "AI systems under audit", value: "All public", icon: "globe" },
      { label: "Implementation time", value: "2 years", icon: "clock" },
    ],
  },
  {
    id: 10,
    title: "Digital Membership From Day One",
    subtitle: "Secure digital identity, government mail, and a clear next-step function in your phone",
    body: "You shouldn't have to go analog in a digital country just because you recently arrived. From day one, people should be able to get a secure digital identity, government mail, a consolidated case overview, bookings, language support, civic information, and a clear next-step function on their phone. This isn't decoration. It's infrastructure. What today looks like a personal number problem is often just a design problem the state hasn't taken seriously yet. Digg has already expanded e-identification for people without Swedish personal numbers and more login options in public e-services. The groundwork is done. Now we need to connect it into a coherent experience. Sweden ranks among the world's most digitized countries – but only if you already have a personal number, a BankID, and know how the Tax Agency works. For everyone else, Sweden is still analog, bureaucratic, and incomprehensible. We're fixing that.",
    quote: "What today looks like a personal number problem is often just a design problem the state hasn't taken seriously yet.",
    quoteAuthor: "",
    category: "Digital Infrastructure",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-10_b716d594.png",
    metrics: [
      { label: "Annual investment", value: "SEK 12 bn", icon: "money" },
      { label: "Reached from day one", value: "200,000+/yr", icon: "people" },
      { label: "Digital services in platform", value: "50+", icon: "building" },
      { label: "Languages in interface", value: "40+", icon: "globe" },
      { label: "Time to digital identity", value: "24 hours", icon: "clock" },
      { label: "Digital export potential", value: "SEK 20 bn/yr", icon: "chart" },
    ],
  },
  {
    id: 11,
    title: "Europe's Easiest Country to Start a Business In",
    subtitle: "From idea to registered company, VAT, bank, and first invoice – on your phone, in your language",
    body: "We're building a multilingual, AI-supported business track where an idea can go from thought to registered company, VAT, bank, accounting support, first quote, and first public procurement without first becoming an expert in Swedish bureaucratic language. Sweden has everything to gain from seeing the entrepreneur in the person who arrives, not just the future employee. Internet logic applies here too: lower the thresholds, open the interfaces, let more people build. Company building should fit in a phone, not first in a binder. Immigrants already start businesses at a higher rate than native Swedes – and they bring global networks, new markets, and business ideas we never would have thought of ourselves. In the US, immigrants have founded over half of all unicorn companies. We want the same force here. Every new entrepreneur gets an AI assistant for accounting and regulatory compliance, a human business mentor, and access to a New Start Fund with microloans and advisory services.",
    quote: "Internet logic applies here too: lower the thresholds, open the interfaces, let more people build.",
    quoteAuthor: "",
    category: "Business & Entrepreneurship",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-11_7ad1303e.png",
    metrics: [
      { label: "Fund capital", value: "SEK 30 bn", icon: "money" },
      { label: "New companies per year", value: "25,000", icon: "building" },
      { label: "New jobs (5 years)", value: "150,000", icon: "people" },
      { label: "Tax revenue (5 years)", value: "+SEK 45 bn", icon: "chart" },
      { label: "Time from idea to company", value: "1 day", icon: "clock" },
      { label: "Languages in business track", value: "40+", icon: "globe" },
    ],
  },
  {
    id: 12,
    title: "From Student to Builder of Sweden",
    subtitle: "Automatic digital transition from graduation to career, research, startup, or public service",
    body: "Someone who has spent years of their life studying here shouldn't be met with an administrative thank you and goodbye. We should have an automatic digital transition track from graduation to employment, research, startup, or public service. AI can help map competence, match against shortage occupations, find co-founders, and connect people to regional innovation environments. The dumbest thing a knowledge nation can do is educate global talent and then actively make it harder for them to stay and contribute. Sweden invests hundreds of millions in each international student's education – and then we do everything we can to push them out. It's like planting a tree, watering it for five years, and then digging it up. Instead, we build a seamless transition: before the student graduates, the system has already mapped opportunities, connected contacts, and suggested next steps. Residence permits for work after graduation should be automatic, not a new bureaucratic hurdle.",
    quote: "The dumbest thing a knowledge nation can do is educate global talent and then actively make it harder for them to stay.",
    quoteAuthor: "",
    category: "Competence & Work",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-12_96504b94.png",
    metrics: [
      { label: "Annual investment", value: "SEK 5 bn", icon: "money" },
      { label: "International students/yr", value: "40,000", icon: "people" },
      { label: "Target: stay after graduation", value: "70% (from 30%)", icon: "chart" },
      { label: "Automatic transition tracks", value: "4 (work/research/startup/public)", icon: "building" },
      { label: "Innovation environments connected", value: "50+", icon: "globe" },
      { label: "Time to residence permit", value: "Automatic", icon: "clock" },
    ],
  },
  {
    id: 13,
    title: "Circular Mobility as Strength",
    subtitle: "Portable credentials, digital competence wallets, and the diaspora as network – not loss",
    body: "We need to stop thinking that mobility only has value if it ends in permanent standstill. In a connected world, people can contribute to Sweden from Malmö, Mumbai, and Madrid at different phases of life. That's why we're building portable credentials, digital competence wallets, easy re-entries, and strong diaspora networks. The diaspora is not a loss. It's a network. Sweden should be a hub in people's lives, not an administrative needle's eye. The old model – come here, stay forever, or disappear – doesn't fit a connected world. Ireland built its tech boom partly through its diaspora. Israel has done the same. India likewise. Sweden has a global diaspora of hundreds of thousands of people with Swedish educations, Swedish networks, and Swedish values. We should make it ridiculously easy to come back, contribute remotely, invest, research, teach, and collaborate – regardless of where in the world you are.",
    quote: "The diaspora is not a loss. It's a network. Sweden should be a hub in people's lives.",
    quoteAuthor: "",
    category: "Mobility & Networks",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-13_5b676d6f.png",
    metrics: [
      { label: "Annual investment", value: "SEK 4 bn", icon: "money" },
      { label: "Swedish diaspora globally", value: "500,000+", icon: "people" },
      { label: "Digital competence wallets", value: "1 million", icon: "globe" },
      { label: "Re-entries per year (target)", value: "25,000", icon: "people" },
      { label: "Diaspora networks", value: "50 countries", icon: "globe" },
      { label: "Implementation time", value: "2 years", icon: "clock" },
    ],
  },
  {
    id: 14,
    title: "Fast and Predictable Rule of Law",
    subtitle: "Track your case like a package – with better law and greater dignity",
    body: "Every person should be able to track their case like you track a package today, but with better law and greater dignity. Clear status, expected processing time, missing documents, next steps, responsible function, translation in your own language. AI can summarize, structure, prioritize, and flag – but the exercise of power must never be hidden behind a black box. Slow opacity is not neutral. It's a political choice. Today, people wait for months, sometimes years, without knowing where in the process they are. They call agencies that don't answer. They send documents that disappear. They live in limbo while their lives tick away. That's not legal certainty – it's legal uncertainty. We're building a system where every case has a clear timeline, where AI flags bottlenecks before they arise, and where no one needs to call an agency to find out what's happening with their life. The Swedish Authority for Privacy Protection's guidelines for AI in public administration give us the framework – now we build the reality.",
    quote: "Slow opacity is not neutral. It's a political choice.",
    quoteAuthor: "",
    category: "Rule of Law & Protection",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-14_76ff2624.png",
    metrics: [
      { label: "Annual investment", value: "SEK 10 bn", icon: "money" },
      { label: "Cases with real-time status", value: "All", icon: "building" },
      { label: "Processing time (target)", value: "-50%", icon: "clock" },
      { label: "Languages in case system", value: "40+", icon: "globe" },
      { label: "People reached per year", value: "300,000+", icon: "people" },
      { label: "Appeals (target)", value: "-60%", icon: "chart" },
    ],
  },
  {
    id: 15,
    title: "Integration as a National Elite Discipline",
    subtitle: "Open dashboard, open APIs, and open testbeds – that's how the internet works, and how a modern country should work",
    body: "We're building an open integration dashboard for the entire country. Municipality by municipality, agency by agency, in real time where possible: time to first job, time to competence decision, school progression, entrepreneurship, housing stability, participation, and trust. And we're opening data, APIs, and testbeds so that civil society, researchers, startups, and municipalities can build better solutions on top of shared infrastructure. That's how the internet works. It's also how a modern country should work. Measure what works, stop winning debates with anecdotes. Every point in this program gets measurable targets and a responsible minister. Results are presented in parliament and on the open platform – accessible in 40 languages – where every citizen can follow progress in their municipality. If we fail, it should be visible. If we succeed, it should be celebrated. We're creating an independent integration authority with the mandate to review, evaluate, and propose changes. Transparency is not a weakness – it's the strongest tool we have.",
    quote: "Measure what works. Stop winning debates with anecdotes.",
    quoteAuthor: "",
    category: "Governance & Transparency",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-15_b924cfee.png",
    metrics: [
      { label: "Annual investment", value: "SEK 5 bn", icon: "money" },
      { label: "Open data platform", value: "40+ languages", icon: "globe" },
      { label: "Responsible ministers", value: "15 (one per point)", icon: "people" },
      { label: "Open APIs", value: "100+", icon: "building" },
      { label: "Monitoring frequency", value: "Real-time", icon: "clock" },
      { label: "Total program cost/yr", value: "~SEK 200 bn", icon: "money" },
    ],
  },
];
