/*
 * Det Nya Sverige – 15 Punkter
 * Grundtes: Problemet är inte människor, det är friktion.
 * Huvudregel: AI där den minskar friktion, människor där de utövar makt.
 * Ton: Direkt, operationell, designtänkande. Integration som onboarding,
 * staten som plattform, data som infrastruktur, AI som hävstång, människan som huvudperson.
 */

export interface DataMetric {
  label: string;
  value: string;
  icon: "money" | "people" | "chart" | "clock" | "building" | "globe";
}

export interface PolicyPoint {
  id: number;
  title: string;
  subtitle: string;
  body: string;
  quote: string;
  quoteAuthor: string;
  category: string;
  metrics: DataMetric[];
  ogImage: string;
}

export const policyPoints: PolicyPoint[] = [
  {
    id: 1,
    title: "Ett Sverige in, inte femton köer",
    subtitle: "En enda digital väg in – med en mänsklig lots och en AI-lots i fickan",
    body: "Vi bygger en enda väg in till Sverige: en digital onboarding, inte en administrativ hinderbana. Varje människa ska möta ett gemensamt gränssnitt där identitet, dokument, språkstöd, hälsokontakt, skolspår, arbetsspår och samhällsinformation hänger ihop. Där finns både en mänsklig lots och en AI-lots i fickan: AI översätter, förklarar, sammanfattar och varnar när något saknas, medan handläggaren gör bedömningar och tar ansvar. Staten ska fungera mer som en smart plattform och mindre som femton myndighetsöar som spelar pingis med människors liv. I dag skickas människor mellan Migrationsverket, Arbetsförmedlingen, Skatteverket, kommunen och Försäkringskassan som om det vore ett rimligt system. Det är det inte. Det är ett designproblem. Digg har redan godkänt e-legitimation för personer utan svenskt personnummer och byggt ut identitetsmatchning – verktygen finns, det som saknas är vilja, tempo och design.",
    quote: "Det som i dag ser ut som ett integrationsproblem är ofta bara ett designproblem som staten ännu inte tagit på allvar.",
    quoteAuthor: "",
    category: "Plattform & Onboarding",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-1_4530788a.png",
    metrics: [
      { label: "Årlig investering", value: "18 mdr kr", icon: "money" },
      { label: "Berörda per år", value: "200 000+", icon: "people" },
      { label: "Myndigheter som kopplas ihop", value: "15+", icon: "building" },
      { label: "Handläggningstid (mål)", value: "-70%", icon: "chart" },
      { label: "Språk i AI-lotsen", value: "40+", icon: "globe" },
      { label: "Full utrullning", value: "24 månader", icon: "clock" },
    ],
  },
  {
    id: 2,
    title: "100-dagarsgaranti för kompetens",
    subtitle: "Ett digitalt kompetenspass som slutar börja i misstro",
    body: "Vi inför ett digitalt kompetenspass. Examina, certifikat, arbetsprover, referenser och erfarenheter ska laddas upp en gång, läsas av maskinellt, jämföras mot svenska krav och landa i ett tydligt besked: godkänt, komplettera detta, eller här finns ett alternativt spår. AI används för att tolka dokument, matcha mot kvalifikationskrav och föreslå kompletteringar. Människan fattar beslutet, men systemet ska sluta börja i misstro. Ett papper som inte passar i en svensk mapp ska inte få radera ett helt arbetsliv. I dag tar validering av utländska utbildningar i genomsnitt 18 månader. Under den tiden kör kirurger taxi och ingenjörer städar trapphus – inte för att det är fel att köra taxi eller städa, utan för att vi slösar bort kompetens vi desperat behöver. Det är inte bara orättvist, det är ekonomiskt vansinne. Sverige rankas tvåa i Global Innovation Index – tänk vad vi kan göra om vi faktiskt använder all den kompetens som redan finns här.",
    quote: "Ett papper som inte passar i en svensk mapp ska inte få radera ett helt arbetsliv.",
    quoteAuthor: "",
    category: "Kompetens & Arbete",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-2_6871597a.png",
    metrics: [
      { label: "Årlig investering", value: "15 mdr kr", icon: "money" },
      { label: "Valideringar per år", value: "90 000", icon: "people" },
      { label: "Max tid till besked", value: "100 dagar", icon: "clock" },
      { label: "Samhällsbesparing", value: "40 mdr kr/år", icon: "chart" },
      { label: "Regionala valideringscentra", value: "50", icon: "building" },
      { label: "Branscher i systemet", value: "120+", icon: "globe" },
    ],
  },
  {
    id: 3,
    title: "Svenska genom arbete, inte före arbete",
    subtitle: "En personlig AI-språkcoach i fickan – kopplad till ditt jobb, din utbildning, din vardag",
    body: "Alla som behöver det får svenska i fickan: en personlig språkcoach med talträning, yrkesordlistor, dialogsimulationer, realtidsöversättning och återkoppling kopplad till just det jobb, den utbildning eller den vardag man befinner sig i. Vi ska inte ha en modell där människor först väntar i åratal på att bli tillräckligt svenska för att börja bidra. Språket lär man sig bäst när det används, och AI gör det möjligt att träna lite, ofta, relevant och på egen nivå. Det här är kanske den mest underskattade hävstången av alla. OECD lyfter AI som särskilt lovande för språkträning i integration. En somalisktalande läkare kan rädda liv på somaliska medan hen lär sig svenska. En arabisktalande ingenjör kan lösa tekniska problem på arabiska redan första veckan. Parallell kompetens och parallellt språk – inte sekventiellt. SFI i sin nuvarande form är en vänthall, inte en startbana. Vi bygger om det från grunden.",
    quote: "Språket lär man sig bäst när det används. Inte i ett klassrum man väntat ett år på att komma in i.",
    quoteAuthor: "",
    category: "Språk & Lärande",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-3_4a486f4d.png",
    metrics: [
      { label: "Årlig investering", value: "22 mdr kr", icon: "money" },
      { label: "Berörda per år", value: "180 000", icon: "people" },
      { label: "Språk i AI-coachen", value: "40+", icon: "globe" },
      { label: "Förväntad BNP-effekt", value: "+0,8% årligen", icon: "chart" },
      { label: "Yrkesbanor med parallellt språk", value: "80+", icon: "building" },
      { label: "Full utrullning", value: "18 månader", icon: "clock" },
    ],
  },
  {
    id: 4,
    title: "Nationell snabbfil till bristyrken",
    subtitle: "Digitala snabbspår med validering, simuleringar och AI-stödda kunskapstest",
    body: "Vi bygger digitala snabbspår till bristyrken med validering, simuleringar, AI-stödda kunskapstest, handledd praktik och betald komplettering. En sjuksköterska ska inte börja om från noll därför att staten saknar fantasi, och en elektriker ska inte fastna mellan pdf:er och pärmar. Tekniken ska användas för att komprimera vägen till svensk licens, inte för att skapa fler väntrum. När någon kan jobbet ska systemet hjälpa till att bevisa det snabbare. Sverige har i dag brist på personal i över 100 yrkeskategorier – från undersköterskor till civilingenjörer, från svetsare till specialistläkare. Samtidigt har vi tiotusentals människor med exakt den kompetensen som sitter fast i ett system designat för att bromsa. Det är som att ha en motorväg med hastighetsbegränsning 30. Vi tar bort de onödiga hastighetsbegränsningarna.",
    quote: "Tekniken ska komprimera vägen till svensk licens, inte skapa fler väntrum.",
    quoteAuthor: "",
    category: "Kompetens & Arbete",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-4_6eec1d5e.png",
    metrics: [
      { label: "Årlig investering", value: "12 mdr kr", icon: "money" },
      { label: "Snabbspår i bristyrken", value: "100+", icon: "building" },
      { label: "Deltagare per år", value: "45 000", icon: "people" },
      { label: "Tid till licens (mål)", value: "-60%", icon: "clock" },
      { label: "Samhällsbesparing", value: "25 mdr kr/år", icon: "chart" },
      { label: "Praktikplatser", value: "30 000/år", icon: "people" },
    ],
  },
  {
    id: 5,
    title: "Första riktiga jobbet inom 180 dagar",
    subtitle: "Från CV-teater till kompetensbevis – AI-matchning som ser potential, inte mallar",
    body: "Vi går från CV-teater till kompetensbevis. AI-stödd matchning kan koppla ihop människor med arbetsgivare utifrån färdigheter, språkprogression, arbetsprov, referenser och faktisk potential – inte bara svenska mallar för personliga brev. Varje person får en kombination av digital coach och mänsklig jobbmatchare. AI ska ersätta väntan, inte människan. Vi ska sluta låtsas att CV-skrivning är integration. I dag tar det i genomsnitt över två år för en nyanländ att få sitt första riktiga jobb. Två år av väntan, osäkerhet och kompetensförlust. Det är inte bara ett individuellt problem – det är ett systemfel. Arbetsgivare skriker efter kompetens medan kompetensen sitter i väntrum. Vi bygger bron mellan dem med teknik som ser vad människor kan, inte bara vad de har skrivit på ett papper.",
    quote: "Vi ska sluta låtsas att CV-skrivning är integration.",
    quoteAuthor: "",
    category: "Kompetens & Arbete",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-5_f959578e.png",
    metrics: [
      { label: "Årlig investering", value: "10 mdr kr", icon: "money" },
      { label: "Matchningar per år", value: "120 000", icon: "people" },
      { label: "Mål: tid till första jobb", value: "180 dagar", icon: "clock" },
      { label: "Arbetsgivare i nätverket", value: "50 000+", icon: "building" },
      { label: "Samhällsekonomisk vinst", value: "35 mdr kr/år", icon: "chart" },
      { label: "Språk i matchningssystemet", value: "40+", icon: "globe" },
    ],
  },
  {
    id: 6,
    title: "Bosätt efter möjlighet, inte efter passivitet",
    subtitle: "Data som visar var jobben, skolorna och bostäderna finns – inte styrning, utan verkliga val",
    body: "Vi använder data för att se var jobben finns, var skolorna fungerar, var bostäderna finns och var vägen till egen försörjning är kortast. Inte för att styra människor som pjäser, utan för att ge dem bättre information och verkliga val. Ett nationellt verktyg ska kunna visa: här finns jobb inom ditt område, här finns språkutbildning, här finns rimlig pendling, här finns bostadsöppningar. Det är märkligt att vi accepterar mer intelligens i en reseapp än i statens beslut om människors framtid. I dag placeras människor i kommuner med hög arbetslöshet, dålig kollektivtrafik och få möjligheter – inte för att det är bäst för dem, utan för att det är enklast för systemet. Det är som att ge någon en karta utan vägar. Vi bygger kartan med vägar, realtidsdata och personliga rekommendationer. Varje kommun som tar emot nyanlända ska kunna visa exakt vilka möjligheter som finns – och mätas på hur väl de levererar.",
    quote: "Det är märkligt att vi accepterar mer intelligens i en reseapp än i statens beslut om människors framtid.",
    quoteAuthor: "",
    category: "Plattform & Onboarding",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-6_96568d86.png",
    metrics: [
      { label: "Årlig investering", value: "8 mdr kr", icon: "money" },
      { label: "Kommuner med realtidsdata", value: "Alla 290", icon: "building" },
      { label: "Datapunkter per kommun", value: "200+", icon: "chart" },
      { label: "Berörda per år", value: "80 000", icon: "people" },
      { label: "Tid till egen försörjning (mål)", value: "-40%", icon: "clock" },
      { label: "Öppna datakällor", value: "50+", icon: "globe" },
    ],
  },
  {
    id: 7,
    title: "Barnen först, alltid",
    subtitle: "Digitalt rustade skolor för flerspråkighet – tekniken är stöd, läraren är ledare",
    body: "Varje nyanlänt barn ska möta en skola som är digitalt rustad för flerspråkighet. Inspelade genomgångar, översatta vårdnadshavarflöden, AI-stött språkstöd, digital studiehandledning, adaptiva övningar och enkla sätt för hem och skola att förstå varandra ska vara standard, inte projektpengar. Men principen är glasklar: tekniken är stöd, läraren är ledare. Vi ska inte bygga botskolor. Vi ska ge bra lärare mycket större räckvidd. Skolverket betonar tydliga ramar och läraransvar för AI i skolan – och det är precis rätt. Men ramarna ska möjliggöra, inte begränsa. Ett barn som talar dari hemma och svenska i skolan har inte ett språk för mycket – det har ett språk mer än de flesta. Varje skola med mer än 20% flerspråkiga elever får dubbla resurser, inte färre. Vi rekryterar 15 000 flerspråkiga pedagoger och betalar dem som specialister. OECD visar att tidiga utbildningsinsatser ger den högsta avkastningen av alla samhällsinvesteringar.",
    quote: "Vi ska inte bygga botskolor. Vi ska ge bra lärare mycket större räckvidd.",
    quoteAuthor: "",
    category: "Barn & Utbildning",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-7_c53a25e2.png",
    metrics: [
      { label: "Årlig investering", value: "35 mdr kr", icon: "money" },
      { label: "Barn som nås", value: "350 000", icon: "people" },
      { label: "Nya flerspråkiga pedagoger", value: "15 000", icon: "people" },
      { label: "Avkastning per krona", value: "7:1 (OECD)", icon: "chart" },
      { label: "Språk i skolplattformen", value: "60+", icon: "globe" },
      { label: "Full utrullning", value: "3 år", icon: "clock" },
    ],
  },
  {
    id: 8,
    title: "Hård mot exploatering, mjuk mot människor",
    subtitle: "Dataanalys som avslöjar utnyttjande – och ett digitalt skyddsrum i fickan för arbetstagaren",
    body: "Vi använder dataanalys och AI för att upptäcka skenanställningar, orimliga lönenivåer, blufföretag, utnyttjande i underleverantörsled och misstänkta mönster av arbetslivskriminalitet långt tidigare än i dag. Samtidigt får arbetstagaren ett digitalt skyddsrum i fickan: kontrakt på sitt språk, lönekoll, rättighetsguide, enkel rapportering, anonym visselblåsning och direktkontakt till stöd. Tekniken ska inte bara hjälpa staten att kontrollera. Den ska hjälpa människan att förstå sin rätt och våga använda den. Arbetslivskriminalitet kostar samhället uppskattningsvis 100 miljarder kronor årligen i förlorade skatteintäkter, snedvriden konkurrens och mänskligt lidande. De som drabbas hårdast är de som har minst makt att försvara sig. Det är en pervers ironi att samma system som gör det svårt att få arbetstillstånd gör det lätt att bli utnyttjad. Vi vänder på det: enkelt att arbeta lagligt, omöjligt att utnyttja någon.",
    quote: "Tekniken ska inte bara hjälpa staten att kontrollera. Den ska hjälpa människan att förstå sin rätt och våga använda den.",
    quoteAuthor: "",
    category: "Rättsstat & Skydd",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-8_ba9f2c48.png",
    metrics: [
      { label: "Årlig investering", value: "8 mdr kr", icon: "money" },
      { label: "Arbetstagare med digitalt skydd", value: "500 000+", icon: "people" },
      { label: "Förväntad besparing", value: "30 mdr kr/år", icon: "chart" },
      { label: "Språk i skyddsrummet", value: "40+", icon: "globe" },
      { label: "Inspektioner med AI-stöd", value: "×5 fler", icon: "building" },
      { label: "Genomförandetid", value: "18 månader", icon: "clock" },
    ],
  },
  {
    id: 9,
    title: "Nolltolerans mot diskriminering",
    subtitle: "Anonymiserad gallring, färdighetsprov före magkänsla och AI-system som granskas för bias",
    body: "Vi gör upp med både analog och digital diskriminering. Offentlig rekrytering ska använda anonymiserad första gallring, färdighetsprov före magkänsla och löpande insyn i utfall. AI-system som används för matchning, urval eller stöd – särskilt i jobb och utbildning – måste kunna granskas, förklaras och stängas av om de reproducerar gamla fördomar. Det räcker inte att digitalisera orättvisor. Sverige ska bli landet som mäter bias lika seriöst som vi mäter budget. EU:s AI-förordning gäller redan stegvis och ger oss ett ramverk – men vi ska gå längre. Diskrimineringsombudsmannen får fyrdubblade resurser och rätt att utdöma kännbara böter. Flerspråkighet blir en formell merit i alla offentliga tjänster. Att tala tigrinja och svenska är inte bara lika bra som att bara tala svenska – det är bättre. Målet: inom fem år ska sysselsättningsgapet mellan inrikes och utrikes födda vara borta.",
    quote: "Det räcker inte att digitalisera orättvisor. Sverige ska bli landet som mäter bias lika seriöst som vi mäter budget.",
    quoteAuthor: "",
    category: "Rättsstat & Skydd",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-9_e69d617f.png",
    metrics: [
      { label: "Årlig investering", value: "6 mdr kr", icon: "money" },
      { label: "Berörda arbetsgivare", value: "85 000", icon: "building" },
      { label: "DO:s nya budget", value: "×4", icon: "money" },
      { label: "Mål: sysselsättningsgap", value: "0% (5 år)", icon: "chart" },
      { label: "AI-system under granskning", value: "Alla offentliga", icon: "globe" },
      { label: "Genomförandetid", value: "2 år", icon: "clock" },
    ],
  },
  {
    id: 10,
    title: "Digitalt medlemskap från dag ett",
    subtitle: "Säker digital identitet, myndighetspost och en tydlig nästa steg-funktion i mobilen",
    body: "Man ska inte behöva bli analog i ett digitalt land bara för att man just kommit hit. Från dag ett ska människor kunna få säker digital identitet, myndighetspost, samlad ärendeöversikt, bokningar, språkstöd, samhällsinformation och en tydlig nästa steg-funktion i mobilen. Det här är inte pynt. Det är infrastruktur. Det som i dag ser ut som ett personnummerproblem är ofta bara ett designproblem som staten ännu inte tagit på allvar. Digg har redan byggt ut e-legitimation för personer utan svenskt personnummer och fler inloggningsalternativ i offentliga e-tjänster. Grundarbetet är gjort. Nu behöver vi koppla ihop det till en sammanhängande upplevelse. Sverige rankas bland världens mest digitaliserade länder – men bara om du redan har ett personnummer, ett BankID och vet hur Skatteverket fungerar. För alla andra är Sverige fortfarande analogt, byråkratiskt och obegripligt. Det fixar vi.",
    quote: "Det som i dag ser ut som ett personnummerproblem är ofta bara ett designproblem som staten ännu inte tagit på allvar.",
    quoteAuthor: "",
    category: "Digital Infrastruktur",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-10_b716d594.png",
    metrics: [
      { label: "Årlig investering", value: "12 mdr kr", icon: "money" },
      { label: "Berörda från dag ett", value: "200 000+/år", icon: "people" },
      { label: "Digitala tjänster i plattformen", value: "50+", icon: "building" },
      { label: "Språk i gränssnittet", value: "40+", icon: "globe" },
      { label: "Tid till digital identitet", value: "24 timmar", icon: "clock" },
      { label: "Digital exportpotential", value: "20 mdr kr/år", icon: "chart" },
    ],
  },
  {
    id: 11,
    title: "Europas enklaste land att starta företag i",
    subtitle: "Från tanke till registrerat bolag, moms, bank och första offert – i mobilen, på ditt språk",
    body: "Vi bygger ett flerspråkigt, AI-stött företagsspår där en idé kan gå från tanke till registrerat bolag, moms, bank, bokföringsstöd, första offert och första offentliga upphandling utan att man först måste bli expert på svensk myndighetssvenska. Sverige har allt att vinna på att se entreprenören i den som kommer hit, inte bara den framtida anställde. Internetlogik gäller här också: sänk trösklarna, öppna gränssnitten, låt fler bygga. Bolagsbyggandet ska få plats i mobilen, inte först i en pärm. Invandrare startar redan företag i högre grad än infödda svenskar – och de tar med sig globala nätverk, nya marknader och affärsidéer vi aldrig hade kommit på själva. I USA har invandrare grundat över hälften av alla unicorn-företag. Vi vill ha samma kraft här. Varje ny företagare får en AI-assistent för bokföring och regelefterlevnad, en mänsklig affärsmentor och tillgång till en Nystartsfond med mikrolån och rådgivning.",
    quote: "Internetlogik gäller här också: sänk trösklarna, öppna gränssnitten, låt fler bygga.",
    quoteAuthor: "",
    category: "Näringsliv & Entreprenörskap",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-11_7ad1303e.png",
    metrics: [
      { label: "Fondkapital", value: "30 mdr kr", icon: "money" },
      { label: "Nya företag per år", value: "25 000", icon: "building" },
      { label: "Nya jobb (5 år)", value: "150 000", icon: "people" },
      { label: "Skatteintäkter (5 år)", value: "+45 mdr kr", icon: "chart" },
      { label: "Tid från idé till bolag", value: "1 dag", icon: "clock" },
      { label: "Språk i företagsspåret", value: "40+", icon: "globe" },
    ],
  },
  {
    id: 12,
    title: "Student till byggare av Sverige",
    subtitle: "Automatiskt digitalt övergångsspår från examen till jobb, forskning, startup eller offentlig tjänst",
    body: "Den som har lagt år av sitt liv på att studera här ska inte mötas av ett administrativt tack och hej. Vi ska ha ett automatiskt digitalt övergångsspår från examen till jobb, forskning, startup eller offentlig tjänst. AI kan hjälpa till att kartlägga kompetens, matcha mot bristyrken, hitta medgrundare och koppla människor till regionala innovationsmiljöer. Det dummaste ett kunskapsland kan göra är att utbilda global talang och sedan aktivt försvåra för den att stanna och bidra. Sverige investerar hundratals miljoner i varje internationell students utbildning – och sedan gör vi allt vi kan för att köra ut dem. Det är som att plantera ett träd, vattna det i fem år och sedan gräva upp det. Vi bygger istället en sömlös övergång: innan studenten tar examen har systemet redan kartlagt möjligheter, kopplat kontakter och föreslagit nästa steg. Uppehållstillstånd för arbete efter examen ska vara automatiskt, inte ett nytt byråkratiskt hinder.",
    quote: "Det dummaste ett kunskapsland kan göra är att utbilda global talang och sedan aktivt försvåra för den att stanna.",
    quoteAuthor: "",
    category: "Kompetens & Arbete",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-12_96504b94.png",
    metrics: [
      { label: "Årlig investering", value: "5 mdr kr", icon: "money" },
      { label: "Internationella studenter/år", value: "40 000", icon: "people" },
      { label: "Mål: stannar efter examen", value: "70% (från 30%)", icon: "chart" },
      { label: "Automatiska övergångsspår", value: "4 (jobb/forskning/startup/offentligt)", icon: "building" },
      { label: "Innovationsmiljöer kopplade", value: "50+", icon: "globe" },
      { label: "Tid till uppehållstillstånd", value: "Automatiskt", icon: "clock" },
    ],
  },
  {
    id: 13,
    title: "Cirkulär rörlighet som styrka",
    subtitle: "Portabla meriter, digitala kompetensplånböcker och diasporan som nätverk – inte bortfall",
    body: "Vi ska sluta tänka att mobilitet bara har värde om den slutar i permanent stillastående. I en uppkopplad värld kan människor bidra till Sverige från Malmö, Mumbai och Madrid i olika faser av livet. Därför bygger vi portabla meriter, digitala kompetensplånböcker, enkla återinträden och starka diasporanätverk. Diasporan är inte ett bortfall. Den är ett nätverk. Sverige ska vara ett nav i människors liv, inte ett administrativt nålsöga. Den gamla modellen – kom hit, stanna för alltid, eller försvinn – passar inte en uppkopplad värld. Irland byggde sin techboom delvis genom sin diaspora. Israel har gjort samma sak. Indien likaså. Sverige har en global diaspora på hundratusentals människor med svenska utbildningar, svenska nätverk och svenska värderingar. Vi ska göra det löjligt enkelt att komma tillbaka, bidra på distans, investera, forska, undervisa och samarbeta – oavsett var i världen man befinner sig.",
    quote: "Diasporan är inte ett bortfall. Den är ett nätverk. Sverige ska vara ett nav i människors liv.",
    quoteAuthor: "",
    category: "Rörlighet & Nätverk",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-13_5b676d6f.png",
    metrics: [
      { label: "Årlig investering", value: "4 mdr kr", icon: "money" },
      { label: "Svensk diaspora globalt", value: "500 000+", icon: "people" },
      { label: "Digitala kompetensplånböcker", value: "1 miljon", icon: "globe" },
      { label: "Återinträden per år (mål)", value: "25 000", icon: "people" },
      { label: "Diasporanätverk", value: "50 länder", icon: "globe" },
      { label: "Genomförandetid", value: "2 år", icon: "clock" },
    ],
  },
  {
    id: 14,
    title: "Snabb och förutsägbar rättsstat",
    subtitle: "Följ ditt ärende som ett paket – med bättre juridik och större värdighet",
    body: "Varje människa ska kunna följa sitt ärende som man i dag följer ett paket, fast med bättre juridik och större värdighet. Tydlig status, väntad handläggningstid, saknade handlingar, nästa steg, ansvarig funktion, översättning på eget språk. AI kan sammanfatta, strukturera, prioritera och flagga – men maktutövning får aldrig döljas bakom en svart låda. Långsam otydlighet är inte neutral. Det är ett politiskt val. I dag väntar människor i månader, ibland år, utan att veta var i processen de befinner sig. De ringer myndigheter som inte svarar. De skickar handlingar som försvinner. De lever i limbo medan deras liv tickar iväg. Det är inte rättssäkerhet – det är rättsosäkerhet. Vi bygger ett system där varje ärende har en tydlig tidslinje, där AI flaggar flaskhalsar innan de uppstår, och där ingen människa behöver ringa en myndighet för att få veta vad som händer med deras liv. IMY:s riktlinjer för AI i offentlig förvaltning ger oss ramverket – nu bygger vi verkligheten.",
    quote: "Långsam otydlighet är inte neutral. Det är ett politiskt val.",
    quoteAuthor: "",
    category: "Rättsstat & Skydd",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-14_76ff2624.png",
    metrics: [
      { label: "Årlig investering", value: "10 mdr kr", icon: "money" },
      { label: "Ärenden med realtidsstatus", value: "Alla", icon: "building" },
      { label: "Handläggningstid (mål)", value: "-50%", icon: "clock" },
      { label: "Språk i ärendesystemet", value: "40+", icon: "globe" },
      { label: "Berörda per år", value: "300 000+", icon: "people" },
      { label: "Överklaganden (mål)", value: "-60%", icon: "chart" },
    ],
  },
  {
    id: 15,
    title: "Integration som nationell elitgren",
    subtitle: "Öppen dashboard, öppna API:er och öppna testbäddar – det är så internet fungerar, och så ett modernt land borde fungera",
    body: "Vi bygger en öppen integrationsdashboard för hela landet. Kommun för kommun, myndighet för myndighet, i realtid där det går: tid till första jobb, tid till kompetensbesked, skolprogression, företagande, bostadsstabilitet, deltagande och tillit. Och vi öppnar data, API:er och testbäddar så att civilsamhälle, forskare, startups och kommuner kan bygga bättre lösningar ovanpå gemensam infrastruktur. Det är så internet fungerar. Det är också så ett modernt land borde fungera. Mät det som fungerar, sluta vinna debatter med anekdoter. Varje punkt i detta program får mätbara mål och en ansvarig minister. Resultaten presenteras i riksdagen och på den öppna plattformen – tillgänglig på 40 språk – där varje medborgare kan följa utvecklingen i sin kommun. Om vi misslyckas ska det synas. Om vi lyckas ska det firas. Vi skapar en oberoende integrationsmyndighet med mandat att granska, utvärdera och föreslå förändringar. Transparens är inte en svaghet – det är det starkaste verktyget vi har.",
    quote: "Mät det som fungerar. Sluta vinna debatter med anekdoter.",
    quoteAuthor: "",
    category: "Styrning & Transparens",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/109756679/fWvW9nTzQXWbjktyLERMVj/og-point-15_b924cfee.png",
    metrics: [
      { label: "Årlig investering", value: "5 mdr kr", icon: "money" },
      { label: "Öppen dataplattform", value: "40+ språk", icon: "globe" },
      { label: "Ansvariga ministrar", value: "15 (en per punkt)", icon: "people" },
      { label: "Öppna API:er", value: "100+", icon: "building" },
      { label: "Uppföljningsfrekvens", value: "Realtid", icon: "clock" },
      { label: "Total programkostnad/år", value: "~200 mdr kr", icon: "money" },
    ],
  },
];

export const categories = [
  "Alla",
  "Plattform & Onboarding",
  "Kompetens & Arbete",
  "Språk & Lärande",
  "Barn & Utbildning",
  "Näringsliv & Entreprenörskap",
  "Rättsstat & Skydd",
  "Digital Infrastruktur",
  "Rörlighet & Nätverk",
  "Styrning & Transparens",
];
